sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.phpunit

env:
  global:
    - deps=""
    - SYMFONY_PHPUNIT_DIR="$HOME/.phpunit"

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env: deps="low"
    - php: 5.6
      env: validator=2.7.*
    - php: 5.6
      env: validator=2.8.*
    - php: 5.6
      env: validator=3.4.*
    - php: 7.0
      env: xdebug="yes"
    - php: 7.1
    - php: 7.2

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$xdebug" != "yes" ]]; then phpenv config-rm xdebug.ini; fi
  - composer self-update
  - if [ "$validator" != "" ]; then composer require --no-update symfony/validator:$validator; fi

install:
  - if [ "$deps" = "low" ]; then composer update --prefer-lowest --prefer-stable; fi
  - if [ "$deps" = "" ]; then composer install; fi

script:
  - if [[ "$xdebug" = "yes" ]]; then vendor/bin/simple-phpunit --coverage-clover=coverage.clover; else vendor/bin/simple-phpunit; fi
  - if [[ "$xdebug" = "yes" ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$xdebug" = "yes" ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
